# -*- coding: utf-8 -*-
"""411410547-許伯瑜

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1V5N2LyRO5xJ2vq4_z-FsEotJ0ph3N2
"""

import zipfile
with zipfile.ZipFile("/content/face_test.zip", "r") as zip_ref:
    zip_ref.extractall("/content/face_test")
print("解壓完成")

!pip install ultralytics

import yaml
import os
import cv2
import glob
import matplotlib.pyplot as plt
from ultralytics import YOLO

DATASET_PATH = "/content/face_test/face_test"

data = {
    "path": DATASET_PATH,

    "train": "train/images",
    "val": "val/images",
    "test": "test/images",

    # ⚠️ 類別一定要跟 MakeSense 標記一致
    "names": {
        0: "angry",
        1: "happy",
        2: "sad"
    }
}

with open("/content/data.yaml", "w") as f:
    yaml.dump(data, f, sort_keys=False)

print("data.yaml 建立完成")

model = YOLO("yolov8n.pt")

model.train(
    data="/content/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="emotion_detection",
    patience=20
)

metrics = model.val()
print(metrics)

best_model = YOLO(
    "runs/detect/emotion_detection/weights/best.pt"
)

results = best_model.predict(
    source=f"{DATASET_PATH}/test/images",
    conf=0.01,
    save=True
)

print("預測完成！")

predict_dirs = glob.glob("runs/detect/predict*")
latest_dir = max(predict_dirs, key=os.path.getmtime)

print("最新 predict 資料夾：", latest_dir)

# 取得所有結果圖片
result_images = os.listdir(latest_dir)

# 顯示圖片
for img_name in result_images:

    img_path = os.path.join(latest_dir, img_name)

    # 讀取圖片
    img = cv2.imread(img_path)

    # BGR → RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 顯示圖片
    plt.figure(figsize=(8,8))
    plt.imshow(img_rgb)
    plt.title(img_name)
    plt.axis("off")
    plt.show()